language: php

php:
  - 7.1
  - 7.2

cache:
  directories:
    - $HOME/.composer/cache/files
    - $HOME/.composer/cache/vcs

install:
  - cp $HOME/.phpenv/versions/$(phpenv global)/etc/conf.d/xdebug.ini /tmp # copy xdebug
  - phpenv config-rm xdebug.ini # remove xdebug for faster composer commands
  - composer install --classmap-authoritative --no-progress

before_script: composer lint

script:
  - composer build
  - phpenv config-add /tmp/xdebug.ini # reenable xdebug for coverage
  - composer coverage-xml
